### ISSUE TITLE
Export templates doesn't contains web templates

### ISSUE THREAD

**Issue by qarmin** [Calinou/godot-builds-ci#17]
![Zrzut ekranu z 2019-06-09 13-17-46](https://user-images.githubusercontent.com/41945903/59158334-0ccf3600-8ab9-11e9-8602-19ef02d6c74f.png)

**Comment by Calinou** [comment]
HTML5 builds are currently broken due to an upstream issue, which will be fixed by https://github.com/godotengine/godot/pull/29482 when it's merged.

**Comment by Calinou** [comment]
The issue has returned due to https://github.com/godotengine/godot/issues/30431, so I'll reopen this for now.

**Edit:** A pull request fixing this has recently been merged, so I'll run a new build and see if it works :slightly_smiling_face: I'll close this once the new build is available.

**Comment by Calinou** [comment]
This has been fixed a while ago, so I'll close this.
