### ISSUE TITLE
No new Mac builds since ~18 August 2019?

### ISSUE THREAD

**Issue by follower** [Calinou/godot-builds-ci#19]
Thanks for your work on these nightly builds.

Based on the following status information (URLs via #16) it appears there have been no new Mac builds since approximately 18 August 2019:

 * https://dev.azure.com/Calinou/godot-builds-ci

 * https://dev.azure.com/Calinou/godot-builds-ci/_pipeline/analytics/stageawareoutcome?definitionId=2&contextType=build

 * https://dev.azure.com/Calinou/godot-builds-ci/_build/results?buildId=628

 * https://dev.azure.com/Calinou/godot-builds-ci/_build?definitionId=2&_a=summary

The current `.dmg` contains a version labeled `3.2.dev.calinou.de4aabe89` (https://github.com/godotengine/godot/commit/de4aabe89b7b68677f145f21c956183bbc92f686) but the current Windows build (via GitLab CI) seems to be based on https://github.com/godotengine/godot/commit/c59da91aad4c73c68e5e2884674f5fb3c3340751 (from looking at the binary in a hex editor :) ).

### Additional context

I encountered this issue while troubleshooting https://github.com/godotengine/godot/issues/27222 and encountering a crash on launch when opened directly from the `.dmg` (which based on the context `lldb` shows seems like it's related to the commit that was reverted by https://github.com/godotengine/godot/commit/0743a07447e613ce0c15f0f55d9284e754c19628#diff-395c1089ded171b1757742cab9e7297d).

**Comment by Calinou** [comment]
Thanks for reporting the issue. Azure Pipelines' scheduled pipelines have a tendency not to start reliably, which is usually fixed by me visiting the page manually. I've just done that, so a new build should be up in a few hours from now :slightly_smiling_face:

**Edit:** New macOS builds are up, so I'll close this issue.

**Comment by follower** [comment]
Thanks, appreciate it, I can confirm I appear to have successfully downloaded `3.2.alpha.calinou.4ee8ecd3e` which was built ~yesterday.

I wonder if it would be worth adding a check to the Gitlab CI script to check if the Azure build is working and/or trigger the build process? :D

**Comment by Calinou** [comment]
@follower Azure Pipelines recently moved to a new pipeline schedule interface, but the old schedules weren't ported over, so I had to recreate a scheduled trigger. It seems to work reliably now.
