### ISSUE TITLE
Make old export templates available

### ISSUE THREAD

**Issue by anissen** [Calinou/godot-builds-ci#20]
It would be nice to have access to old export templates to be able to debug issues with exported projects or as a work-around for issues in new export templates.

**Comment by Calinou** [comment]
I used to do this a while ago, but it made deployment more complex for little gain. Moreover, I don't have a whole lot of space left on my VPS, which means I could only keep a few versions available. Since a new build is published every day, it means you'd only be able to go a few days back.

**Comment by anissen** [comment]
Okay, that makes sense in the context of the service you provide. Thanks for the explanation.
