### ISSUE TITLE
Android_source.zip

### ISSUE THREAD

**Issue by himaghnam** [Calinou/godot-builds-ci#21]
Android custom template is missing. It would be amazing to have that.

**Comment by Calinou** [comment]
https://github.com/Calinou/godot-builds-ci/commit/337195a28844ff65f669212466af06c7d974537b implements an initial version of this. However, I realized that both ZIPs will overwrite each other, which means only one of the AARs is available (either debug or release, depending on which build is finished first). I'll look at fixing this ASAP.

**Comment by Calinou** [comment]
`android_source.zip` should now contain both debug and release AARs as of https://github.com/Calinou/godot-builds-ci/commit/68cadc232ff4b4bb39ac0e1cda74e1d788bbaeb2.

@gamergamesz Please test this, I'll close the issue if it's confirmed to work :slightly_smiling_face:

**Comment by himaghnam** [comment]
Working, rest left the build bug reported in godot.
