### ISSUE TITLE
Windows export templates missing

### ISSUE THREAD

**Issue by Techjar** [Calinou/godot-builds-ci#22]
The Windows templates are suddenly missing from the Windows + Linux + Android + HTML5 package. This is a very new issue as I just downloaded it a couple weeks ago and everything was included.

**Comment by Calinou** [comment]
All Windows builds were failing due to https://github.com/godotengine/godot/issues/34092. I just started a new build; Windows builds should be available again in ~2 hours if everything goes well.

**Comment by Calinou** [comment]
This should be fixed now: https://gitlab.com/Calinou/godot-builds-ci/pipelines/100755565
