### ISSUE TITLE
Editor nightly build is not updated anymore

### ISSUE THREAD

**Issue by IriaSomobu** [Calinou/godot-builds-ci#24]
First of all, I want to say huge "thank you" for running godot build CI and website for such a long time.

Recently I noticed that editor builds on [archive.hugo.pro](https://archive.hugo.pro/builds/godot/master/editor/) are not updating anymore; it seems that latest Linux build is dated back to 2022-12-04 (commit godotengine/godot@015dc492d).

Is there any possibility that nightly builds would come back?

**Comment by Calinou** [comment]
I don't plan to update those builds anymore, as GitLab CI stopped providing unlimited free builds for public projects (unless specifically approved as a large, established open source project – and my repository is just a personal one).

Moving to GitHub Actions is a lot of work; if it is to be done, I would rather do this as part of the @godotengine organiztaion. In the future, we intend to provide official nightly builds (most likely in a dedicated repository of the @godotengine organization). There's no ETA for this though.

I've updated the website accordingly: https://hugo.pro/projects/godot-builds/

**Comment by IriaSomobu** [comment]
If 4x3Ghz threads / 3.8Gb RAM / ~10Gb disk is enough for godot build, I can setup gitlab runner for you on the same machine I'm running gitlab CI for my own project.

**Comment by akien-mga** [comment]
I think we'll start doing official nightly builds with the same build server used for official beta/stable releases some time after the 4.0 release. It's pretty powerful, we just need to have some time to set things up for continuous delivery.
