### ISSUE TITLE
The download links for the export templates are broken.

### ISSUE THREAD

**Issue by Ace-Dragon** [Calinou/godot-builds-ci#3]
When I click the link to download the latest version of the export templates (as of the last couple of weeks), I get a long page filled with garbled text instead of a file that downloads (Google Chrome, latest version on Win10 64 bit).

I'm not sure if this will be read, but the builds page says to report here.

**Comment by Calinou** [comment]
This was due to a server configuration mistake and should now be fixed (`.tpz` didn't have an `application/zip` MIME type so Chrome attempted to display it as text instead).

Please try again after clearing your cache.
