### ISSUE TITLE
Idea: windows image that contain all needed programs to build godot

### ISSUE THREAD

**Issue by sami8github** [Calinou/godot-builds-ci#5]
If is it possible and if you like the idea : to provide a windows image that contain all needed programs and setups and every program needed to build godot and its templates.
like that to build godot all you need is install this image and execute the command.
its possible then to install this image on usb drive and boot to it build godot and back to normal windows.

**Comment by Calinou** [comment]
In my experience, it's already quite simple to build Godot on a fresh Windows system. Note that it will be easier on Windows 8 and later, as you won't need to upgrade PowerShell manually to install Scoop.

Try following these steps:

1. Install [Scoop](https://scoop.sh/).
2. Open a command prompt and type the following command to install the tools required to compile Godot:
```
scoop install gcc git python scons yasm
```
3. Clone the Godot source code and move into the cloned directory:
```
git clone --depth=1 https://github.com/godotengine/godot.git
cd godot
```
4. Compile an optimized editor build (for instance):
```
scons platform=windows target=release_debug use_lto=yes progress=no
```
5. You should find binaries in the `bin/` directory of the Godot source directory.

**Comment by sami8github** [comment]
Very nice bro, Thank you a lot
