### ISSUE TITLE
The last modified time for godot is 22-Aug

### ISSUE THREAD

**Issue by sami8github** [Calinou/godot-builds-ci#6]
http://www.visiospark.com/last-modified-time-checker/
The last modified time for godot for macos  is up to date (26 Aug), but godot for other platforms is 22-Aug
it seems that only godot for macos and its template are uploaded ,(but godot for other platforms and its templates are not uploded) , is there a problem in builds or uploads ..?

**Comment by Calinou** [comment]
The Windows editor build is failing, so new builds aren't being deployed for now (except for macOS and iOS, as those are built on a different CI platform).

I reported the issue upstream: https://github.com/godotengine/godot/issues/21472

**Comment by qarmin** [comment]
PR https://github.com/godotengine/godot/pull/21474 was merged but new builds still are not showing.

**Comment by Calinou** [comment]
@qarmin That particular build issue is now fixed on my end (latest builds are from 2018-08-28 right now). However, there was an issue with the script failing to fetch resources required to build Godot, so new builds weren't deployed this morning. I restarted the failing jobs so these should be available today.

**Edit:** New builds are now available, so I'll close this issue.

**Comment by qarmin** [comment]
I downloaded Windows 64 ZIP but still is version https://github.com/godotengine/godot/commit/5df91099c74889d48d05de9ad677f24ac71a0d48
![aaaaaaaa](https://user-images.githubusercontent.com/41945903/44832212-34d86180-ac2a-11e8-90b6-dda44867b2e0.png)

**Comment by qarmin** [comment]
Something is wrong with 64bit version, because 32bit works fine
