### ISSUE TITLE
Export Templates

### ISSUE THREAD

**Issue by ondesic** [Calinou/godot-builds-ci#8]
Are current 3.1alpha export templates available?

**Comment by Calinou** [comment]
Yes, they're listed at the bottom of [this page](https://hugo.pro/projects/godot-builds/) below **Windows**, **macOS** and **Linux** :slightly_smiling_face:

**Comment by ondesic** [comment]
Thank you. I've tried that.  However, Godot recognizes the templates listed as 3.1.dev and not 3.1.alpha

**Comment by Calinou** [comment]
> However, Godot recognizes the templates listed as 3.1.dev and not 3.1.alpha

Actually, it's an issue on my side — I forgot to update the `version.txt` for 3.1-alpha. [I just updated it](https://github.com/Calinou/godot-builds-ci/commit/0929eb550ecde1bfc4d00f652c4de0224ac1deaa), so export templates should be installable again starting from tomorrow.
